services:
  api:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - database
    env_file:
      - .env
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npx prisma generate &&
        node dist/server.js
      "

  database:
    image: postgres
    restart: always
    volumes:
      - ./volumes/db:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432