services:
  api:
    build: .
    command: npm run dev
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - database
    networks:
      - private_network
      - public_network
    env_file: ".env.docker"

  database:
    image: postgres
    restart: always
    volumes:
      - ./volumes/db:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: visus
    ports:
      - 5432:5432
    networks:
      - private_network

networks:
  public_network:
    driver: bridge
  private_network:
    driver: bridge

